### ISSUE TITLE
Library Errors on Mac

### ISSUE THREAD

**Issue by 18santos123** [pardeike/HarmonyRimWorld#11]
Hello, recently I have been trying to get the empire mod to work on rimworld, but it crashes as soon as I click a button on its in-game ui. I've tried to narrow down what the problem could be and i'm pretty sure it's due to a series of "could not load library" errors. These errors are present when harmony is the only mod installed and they go away when the game has 0 mods. I'm still not 100% sure if these errors are causing my problems with empire, but I would greatly appreciate it if you could check out my log to see if there is an easy fix to my library errors. Btw I am on mac
[Player.log](https://github.com/pardeike/HarmonyRimWorld/files/5713999/Player.log)

**Comment by pardeike** [comment]
I sometimes get reports like this. All of them are related to a corrupt Steam download that makes RimWorld behave like that. Reinstall RimWorld from scratch. The harmony mod is used by several hundred thousands of users without problem.
