### ISSUE TITLE
Game shows a version update but the version's tag has not changed.

### ISSUE THREAD

**Issue by codeninja** [pardeike/HarmonyRimWorld#12]
Rimworld is showing a need to update but it's not possible to update via steam. And if this is a new version, does the tag for the rease needs to be bumped to distinguish them?

**Comment by pardeike** [comment]
When you say "RimWorld is showing a need to update", what do you mean by that? I am not aware of vanilla RimWorld doing that.

**Comment by PavelDB** [comment]
https://user-images.githubusercontent.com/77897715/105611748-0cc79b00-5daf-11eb-9789-8ce9a43c8ead.png
I think this is what he means.

**Comment by pardeike** [comment]
Yes. That is a mod. And that mod displays the version by looking into the mods repository (this here) and finding this file: `About/ModSync.XML`. I think it does that correctly. 

The reason you cannot update the mod on Steam is that I am still working on that version and have not created a release yet.

**Comment by ghost** [comment]
I can confirm this. Mod Manager is telling me that a new version is available but you have not released a new version. I can only assume this is because you are committing work-in-progress changes directly to the master branch.

(I do not use Steam)

**Comment by pardeike** [comment]
See https://github.com/fluffy-mods/ModManager/issues/143
I will not change my best practices, better go and make the Issue being fixed.
