### ISSUE TITLE
No release for version update

### ISSUE THREAD

**Issue by AngleWyrm10** [pardeike/HarmonyRimWorld#15]
Manifest.xml / [version number](https://github.com/pardeike/HarmonyRimWorld/commit/39228e4016ac0e77fdbbac50e4ef973b91a38728#diff-a8ccaa9afed5814a29feae24970b0e323d9d01fa508c6e10b690f459cfbb3389) has been changed, but there's no release associated with the new version number.

This results in notifying every player on Steam that a new version is available, but downloading the linked latest release doesn't resolve the issue.

Solution: Publish a new release for the new version number.

**Comment by pardeike** [comment]
See https://github.com/pardeike/HarmonyRimWorld/pull/14
