### ISSUE TITLE
harmony.log.txt on desktop, Windows

### ISSUE THREAD

**Issue by Shadlock0133** [pardeike/HarmonyRimWorld#16]
I think this is the mod that creates `harmony.log.txt` file on desktop. If I'm wrong, sorry.

While I understand that this file might be useful for debugging, having it on desktop is kinda annoying. Maybe add option to disable it and/or move it to more related place (e.g. rimworld game folder)?

**Comment by pardeike** [comment]
This is the responsibility of the mod developer to remove debugging code from production releases.
