### ISSUE TITLE
Is it possible to harmony patch the internal class from other assembly?

### ISSUE THREAD

**Issue by QQLQ** [pardeike/HarmonyRimWorld#18]
Hi Brrainz, your work is epic. I made several mods with Harmony, but recently i met a problem.
Tring to patch a internal class from other assembly, but said "member' is inaccessible due to its protection level".  
Harmony is able to patch the private class, thus what about internal class from ohter assembly? Is it possible to patch it? Or I just miss some important things?

**Comment by pardeike** [comment]
Use a TargetMethod in your patch class:
<https://harmony.pardeike.net/articles/patching-auxilary.html#targetmethod>
You should also look at TypeByName or Method("...") in
<https://harmony.pardeike.net/api/HarmonyLib.AccessTools.html>
