### ISSUE TITLE
How to patch a getter in internal class?

### ISSUE THREAD

**Issue by QQLQ** [pardeike/HarmonyRimWorld#19]
Greetings, Brrainz, thank you for your last reply and that did huge help.
One thing that I found that is that I was trying to patch a getter in internal class. Use TypeByName and TargetMethod did solve the access to internal class problem, but patching a getter needs annotations like [HarmonyPatch(typeof(....),"somegetter",MethodType.Getter)], by doing so the whole thing cameback to its start----that typeof() does not  allow me to access internal class from another assembly.
So anything I could do with that?

**Comment by pardeike** [comment]
You use TargetMethod *instead* of the annotation (keep an empty annotation on the class so Harmony will consider it). In there you use all the reflection to return the MethodInfo. Properties have a reflection method to get their get_ or set_ methods.
