### ISSUE TITLE
Unable to load mods

### ISSUE THREAD

**Issue by YovelB** [pardeike/HarmonyRimWorld#22]
I am running RimWorld version 1.3.3325 and when trying to load the new library release V1.3.00
with the following mod latest version V4.5-Hotfix.
https://github.com/CombatExtended-Continued/CombatExtended

It appears the normal initialization of RimWorld is starting and when it finishes it only shows a big buggy and empty pane with a debug title. Without these mods, the game worked. Though, when I reapplied them it didn't.

So in order to fix the problem, I installed the mods one at a time and it worked.
Afterward, I tried reproducing the error unsuccessfully.
You can mark this bug as an archive if someone might ever run into it.

**Comment by pardeike** [comment]
This is a typical Steam corruption error. Surprisingly quite common.
