### ISSUE TITLE
Modlist won't appear

### ISSUE THREAD

**Issue by pardeike** [pardeike/HarmonyRimWorld#23]
When I try to open the modlist from the main menu it doesn&#39;t open and produces these two errors, Mod Manager-- the only active mod other than official<br> dlc-- is likely not the culprit as I have tried to open it while unsubscribed to the mod and the issue still persisted.<br><br>Tried loading mod with the same packageId multiple times: UnlimitedHugs.AllowTool. Ignoring the duplicates.<br>C:\Games\Steam\steamapps\workshop\content\294100\761421485<br>C:\Games\Steam\steamapps\workshop\content\294100\2542134202<br>UnityEngine.StackTraceUtility:ExtractStackTrace ()<br>Verse.Log:Error (string)<br>Verse.ModLister:TryAddMod (Verse.ModMetaData)<br>Verse.ModLister:RebuildModList ()<br>RimWorld.Page_ModsConfig:PreOpen ()<br>ModManager.Page_BetterModConfig:PreOpen ()<br>Verse.WindowStack:Add (Verse.Window)<br>ModManager.Patch_Replace_Page_ModsConfig:OpenModsConfig ()<br>Verse.ListableOption:DrawOption (UnityEngine.Vector2,single)<br>Verse.OptionListingUtility:DrawOptionListing (UnityEngine.Rect,System.Collections.Generic.List&#x60;1&lt;Verse.ListableOption&gt;)<br>(wrapper dynamic-method) RimWorld.MainMenuDrawer:RimWorld.MainMenuDrawer.DoMainMenuControls_Patch0 (UnityEngine.Rect,bool)<br>RimWorld.MainMenuDrawer:MainMenuOnGUI ()<br>Verse.UIRoot_Entry:DoMainMenu ()<br>Verse.UIRoot_Entry:UIRootOnGUI ()<br>Verse.Root:OnGUI ()<br><br>Root level exception in OnGUI(): System.TypeLoadException: Could not load type of field &#39;ModManager.CrossPromotionManager:_appId&#39; (0) due to: Could not resolve type with token 0100001c (from typeref, class&#x2F;assembly Steamworks.AppId_t, Assembly-CSharp-firstpass, Version&#x3D;0.0.0.0, Culture&#x3D;neutral, PublicKeyToken&#x3D;null) assembly:Assembly-CSharp-firstpass, Version&#x3D;0.0.0.0, Culture&#x3D;neutral, PublicKeyToken&#x3D;null type:Steamworks.AppId_t member:(null) signature:&lt;none&gt;<br>  at ModManager.Page_BetterModConfig.PreOpen () [0x0003a] in &lt;f9d476bc2c4f414bac4bbeaca4eafac0&gt;:0 <br>  at Verse.WindowStack.Add (Verse.Window window) [0x0001f] in &lt;99518a644a3e4a7ea3fde566568df84a&gt;:0 <br>  at ModManager.Patch_Replace_Page_ModsConfig.OpenModsConfig () [0x0000a] in &lt;f9d476bc2c4f414bac4bbeaca4eafac0&gt;:0 <br>  at Verse.ListableOption.DrawOption (UnityEngine.Vector2 pos, System.Single width) [0x00040] in &lt;99518a644a3e4a7ea3fde566568df84a&gt;:0 <br>  at Verse.OptionListingUtility.DrawOptionListing (UnityEngine.Rect rect, System.Collections.Generic.List&#x60;1[T] optList) [0x00037] in &lt;99518a644a3e4a7ea3fde566568df84a&gt;:0 <br>  at (wrapper dynamic-method) RimWorld.MainMenuDrawer.RimWorld.MainMenuDrawer.DoMainMenuControls_Patch0(UnityEngine.Rect,bool)<br>  at RimWorld.MainMenuDrawer.MainMenuOnGUI () [0x00242] in &lt;99518a644a3e4a7ea3fde566568df84a&gt;:0 <br>  at Verse.UIRoot_Entry.DoMainMenu () [0x0001f] in &lt;99518a644a3e4a7ea3fde566568df84a&gt;:0 <br>  at Verse.UIRoot_Entry.UIRootOnGUI () [0x0001c] in &lt;99518a644a3e4a7ea3fde566568df84a&gt;:0 <br>  at Verse.Root.OnGUI () [0x0003d] in &lt;99518a644a3e4a7ea3fde566568df84a&gt;:0 <br>UnityEngine.StackTraceUtility:ExtractStackTrace ()<br>Verse.Log:Error (string)<br>Verse.Root:OnGUI ()

-- submitted by BrenMoose24@yahoo.com

**Comment by RosyMaplePheonix** [comment]
Person who placed report here, the issue seemed to resolve itself after I deleted and reinstalled the local files

**Comment by pardeike** [comment]
Pretty common. Steam is like that sometimes
