### ISSUE TITLE
Providing example Postfix method

### ISSUE THREAD

**Issue by HerrKai** [pardeike/HarmonyRimWorld#24]
Hello, a friend and I are trying to get started with modding using Harmony. We did manage to get a basic mod set up and running in the game (logging `Hello world`). However, upon trying to create a simple `Postfix` by following an online guide we noticed that the code snippet does not appear to be running. I have provided our code below:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using RimWorld;
using Verse;
using HarmonyLib;

namespace Testing
{
    [StaticConstructorOnStartup]
    public static class Class1
    {
        private const string PACKAGE_ID = "ChrisHerrKai.Testing.Testing";
        static Class1()
        {
            Harmony harmonyInstance = new Harmony(PACKAGE_ID);
            harmonyInstance.PatchAll();
            Log.Message("Hello World!");
        }
    }

    [HarmonyPatch]
    public static class Building_Battery_Patch
    {
        [HarmonyPatch(typeof(Building_Battery), nameof(Building_Battery.PostApplyDamage))]
        public static void PostApplyDamage()
        {
            Log.Message("Battery got damaged");
        }
    }
}
```

We found little to no official guidelines to get started with harmony, it's features or examples on various features like adding items, modifying existing content, etc. Do you have any resources available to make it easier for people to get started with modding using harmony?

**Comment by pardeike** [comment]
Please find the link to the official discord server on the GitHub readme page and join it. There, many many developers can help you. Also, check out all the source code to my own RimWorld mods on the same GitHub account. 

Issues here on GitHub are less ideal for basic support questions.

**Comment by pardeike** [comment]
Ps: your postfix neither is called “Postfix” nor have you use the [HarmonyPostfix] annotation. Please refer to the documentation on how to write patch methods.
