### ISSUE TITLE
Newest Harmony version (Oct 5) causes main menu to fail to load

### ISSUE THREAD

**Issue by Queenofdragons6** [pardeike/HarmonyRimWorld#31]
Playing on RimWorld v1.3.3387 GOG version
Trying to play with the newest version of Harmony installed causes the main menu to not load. The music won't play and the buttons won't show up. Only the menu background will be present.
Is Harmony v1.5 meant for 1.3 or 1.4?

**Comment by pardeike** [comment]
I did not change the code in Harmony. It does work for 1.3 and 1.4 since it doesn’t do much on its own. All I did was to add the necessary info to make 1.4 show it in non-red color. Something is wrong with your setup but I can’t tell you what.

**Comment by Queenofdragons6** [comment]
Hmm. Odd. It worked again when I went back to the previous version of Harmony so...maybe it's a mod conflict of some kind?

**Comment by pardeike** [comment]
No idea. I tested Harmony in 1.3 and 1.4 and as expected, it just loads fine:
![image](https://user-images.githubusercontent.com/853584/194461608-883b1de7-6f6c-4aa1-aff7-420a6196b6da.png)

**Comment by Queenofdragons6** [comment]
Oh wait, I think I figured out the issue: I'd unknowingly had Harmony nestled in an additional folder. It runs okay now.
