### ISSUE TITLE
24 days before dlc biotech.

### ISSUE THREAD

**Issue by H2oSpez** [pardeike/HarmonyRimWorld#33]
so mod was made before actual dlc came out , if i run it with biotech game do a loop of 10 work at the time ( can see in dev log ) and pawn stuck in place .

**Comment by pardeike** [comment]
The Harmony mod does not cause this. You need to find the mod that uses Harmony

**Comment by H2oSpez** [comment]
But i dontuse anymod exept harmonyitself. A onece more tell that biotech
dlc brake with harmony

2022-10-30, sk 02:14, Andreas Pardeike ***@***.***> rašė:

**Comment by H2oSpez** [comment]
please dont close before its actualy bug and not fixed. i tested by removing all mods from my list and left only DLC + Core. all stock no moded or file edited.  and i am not only persone who gets same bug. ( YES bug dont happen if we dont use Biotech dlc) so please cheak dlc files . i give 100% there is something. mod was made before dlc so its defenetly no support it

**Comment by H2oSpez** [comment]
simply run dev fast map. place stock pile with 5 piles of logs. spawn few more pawns to get bug happen faster. set all pawns to construct and place a lot of walls to start doing. after 10-15 second some one just stand next to the wall saying that he try go to storage take something same time bug mentioned about weapon. i think that they try to equip log as weapon even game tells them to put log on soulder or inventory.

**Comment by H2oSpez** [comment]
Twid
![image_2022-10-30_131117624](https://user-images.githubusercontent.com/116980939/198875540-b411bf8e-82c0-4c91-bb28-4c0576bc75c2.png)
dle started 10 jobs in one tick. newJob=HaulToCell (Job_6975) A=Thing_WoodLog25105 B=(142, 0, 131) jobGiver=null jobList=(HaulToCell (Job_6965) A=Thing_WoodLog25105 B=(142, 0, 131)) (HaulToCell (Job_6966) A=Thing_WoodLog25105 B=(142, 0, 131)) (HaulToCell (Job_6967) A=Thing_WoodLog25105 B=(142, 0, 131))
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
Verse.AI.JobUtility:TryStartErrorRecoverJob (Verse.Pawn,string,System.Exception,Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:StartJob (Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool,System.Nullable`1<bool>,bool,bool)
Verse.AI.Pawn_JobTracker:StartJob
