### ISSUE TITLE
How to get an instance of the internal class?

### ISSUE THREAD

**Issue by Release** [pardeike/HarmonyRimWorld#34]
In issue #18 gives a solution on how to patch an internal (or private) class. And how to get its instance in the "Prefix" or "Postfix" methods?

**Comment by pardeike** [comment]
Wrong repository. Please report bugs in https://github.com/pardeike/Harmony and for support questions please join the official discord: https://discord.gg/xXgghXR

**Comment by Release** [comment]
Thanks! Sorry I didn't notice when I added it. Looks like I didn't use the right tab.
