### ISSUE TITLE
Error on game start and non working save file since update on 13/03/2024

### ISSUE THREAD

**Issue by FardaleM** [pardeike/HarmonyRimWorld#37]
Since the update to the mod on 13/03/2023, I get errors when starting the game. Here are the logs: [harmony_error.txt](https://github.com/pardeike/HarmonyRimWorld/files/14592305/harmony_error.txt)

Also, when loading my save file, the colonists do not do any new tasks. They just finish what they do at the moment and then stand still and also cannot be forced to do anything.

My game version is: 1.4.3901

I am not sure where I should report this error, so please point me to the correct place if it is not here.

Here is the list of mod I have installed:
 - Harmony
 - Core
 - Biotech
 - Vanilla Expanded Framework
 - Alpha Animals
 - Apparello 2
 - [SYR] Set Up Camp
 - ReGrowth: Core
 - [FSF] Fith Vanishes With Rain
 - HugsLib
 - Giddy-up! Core
 - Giddy-up! Ride and Roll
 - ReGrowth: Boiling
 - Replace Stuff
 - RunAndGun
 - Erin's Japanese Furniture
 - More Furniture (Continued)
 - More Sculpture
 - Vanilla Furniture Expanded - Art

**Comment by FardaleM** [comment]
It is not fixed with the last update.

**Comment by pardeike** [comment]
It is a problem with HugsLib that has to be fixed.

**Comment by Drift91** [comment]
I fail to understand how it could possibly be due to HugsLib when it hasn't updated since 2022 and it was working fine yesterday. Did RimWorld itself update? Because I can't find any files in my 'core' DLC folder that have been modified recently. I've tested with just Harmony and HugsLib along with the vanilla game. If any sort of conflict is occurring between Harmony and HugsLib I can only assume it would be due to an update, and the only thing that's updated that I'm aware of is Harmony. Are you sure you reverted the 1.4 version correctly?

**Comment by AlyxMS** [comment]
> It is not fixed with the last update.

It is. However 1.7.0.0 is mistakenly released again as 1.7.1.0.

Download the actual 1.7.1.0 from the code page and it's fixed.

----

Also HugsLib is not the only one that has an issue with the update. In my testing, Humanoid Alien Races and MadSkillz also threw errors.

**Comment by Drift91** [comment]
> Also HugsLib is not the only one that has an issue with the update. In my testing, Humanoid Alien Races and MadSkillz also threw errors.

For me Giddy-Up! Caravan is the one that throws an error. I've checked out v1.5.0.0 and I'm currently updating MSVC2022, will report back the results once I compile it.

@pardeike Is there a particular reason you took down the old downloads for versions earlier than 1.7.0.0? If they were still up that would be saving a lot of headaches, as 98% of the community probably don't know how to compile C# or what an IDE even is.

**Comment by Drift91** [comment]
So I just went to replace the DLL in my mods folder after making a local copy, and suddenly the filesystem's "last modified" time on the original file caught my eye. This is 100% Valve's fault. I absolutely adore how Steam will update to the broken version in under an hour but can't pull it's head out of it's ass for over 3 hours when a hotfix is released.

@pardeike Apologies, everything seems to be working fine after verifying my game files to force an update. Might want to temporarily put some sort of notice on the Steam page about it.

**Comment by pardeike** [comment]
No I am tired of Steam. It has caused me endless troubles.

**Comment by pardeike** [comment]
Btw, new Harmony is more strict on IL changes. All problems come from incorrect applied patches that old Harmony sort of tolerated. I verfied that on the example of HugsLib myself.
