### ISSUE TITLE
The 1.7.1.0 release is actually 1.7.0.0 and does not revert in 1.4

### ISSUE THREAD

**Issue by AlyxMS** [pardeike/HarmonyRimWorld#38]
Using 1.7.1.0 downloaded from the release page, in about.xml, it actually shows
```
<modVersion>1.7.0.0</modVersion>
```
and there is no "1.4" folder. So it actually is the old version.

I suspect the situation is the same in Steam Workshop, as I was previously using that and received the same error as 1.7.0.0. It also showed in-game as 1.7.0.0

So far only "download sourcecode" from the github page actually gets you 1.7.1.0. Release page and Steam Workshop both gets you 1.7.0.0.

**Comment by pardeike** [comment]
Steam is the problem. You need to resub and maybe even quit Steam.

**Comment by AlyxMS** [comment]
> Steam is the problem. You need to resub and maybe even quit Steam.

If the steam workshop problem is fixed, then great. But even then the released version on github is still wrong. See images:

<img width="966" alt="1" src="https://github.com/pardeike/HarmonyRimWorld/assets/7328128/481e378b-add8-49a8-9442-08dab86aff00">
<img width="1188" alt="2" src="https://github.com/pardeike/HarmonyRimWorld/assets/7328128/3e5cacf1-3f89-4da6-9eaf-6bcbb060d037">

Shows 1.7.1.0, but file is actually 1.7.0.0

And yes, this zip file does not have a "1.4" folder, would error in 1.4 and is identical to 1.7.0.0.

**Comment by pardeike** [comment]
Yes, Steam is correct and the problem was that I used the old zip to upload. That upload is now fixed.
