### ISSUE TITLE
RimWorld Version 1.1 Support

### ISSUE THREAD

**Issue by Lakuna** [pardeike/HarmonyRimWorld#39]
I'm in the process of updating my mods to support RimWorld version 1.5, but I'd like them to maintain backwards compatibility with RimWorld versions 1.0-1.4. I currently include `0Harmony.dll` (version 1.2.0.1) in the 1.0 versions of my mods, and use the Harmony mod for versions 1.1-1.4. This works, but I am wondering if it is recommended to include `0Harmony.dll` for the 1.1 version as well, given that neither the Steam Workshop listing nor `LoadFolders.xml` seem to indicate support for that version of RimWorld. `README.md`, old GitHub issues, and a cursory Google search indicate that my current approach is correct, but I'd like to make sure - especially since the most recent update seems to put versions 1.1 and 1.5 on Harmony 2.3.1.1 while versions 1.2-1.4 are on Harmony 2.2.2.

**Comment by pardeike** [comment]
Rimworld 1.1 or older should use Harmon 1.2.0.1 and it should be packaged with each mod.
