### ISSUE TITLE
Prison Labor / Harmony

### ISSUE THREAD

**Issue by Wolvgar** [pardeike/HarmonyRimWorld#4]
Log https://gist.github.com/f1dec773fcd6888839d4048dfd998dd5

Hey there my load order for test
Harmony
Core
Hugslib
Jectools
Prison Labor

Throwing me 2 Errors
PrisonLaborException: FindOperandAfter() didn't find any lines. Trace:  at PrisonLabor.HarmonyPatches.HPatcher.FindOperandAfter (System.Reflection.Emit.OpCode[]

HarmonyLib.HarmonyException: Patching exception in method virtual System.Void RimWorld.Dialog_BillConfig::DoWindowContents(UnityEngine.Rect inRect) ---> System.Exception: Wrong null argument: ldloc.s NULL [Label58, Label59, Label60]

Maybe you have an idea whats going on and can fix if it is on your side. <3 Thanks

**Comment by pardeike** [comment]
Sorry, but I cannot give you support for random mods. With over 6000 mods in total and many using Harmony, it would eat up my time completely.

Obviously you should as the author of PrisonLabor about this.

**Comment by Wolvgar** [comment]
Thanks will do
