### ISSUE TITLE
Open Question: dealing with failed Harmony patches in RimWorld

### ISSUE THREAD

**Issue by Vectorial1024** [pardeike/HarmonyRimWorld#41]
I don't know where else to put this; feel free to link this to elsewhere which may be more suitable.

The problem is this: in RimWorld 1.5, `Verse.Log::Error` no longer forces the appearance of the debug log when dev-mode is off, which makes a lot of errors "invisible". At least this is the observation on my side.

This reduces our general awareness of bugs, which can be a problem. For example, failed patches that generate a red error is now invisible when dev-mode is off, which means regular users simply do not notice any errors until they somehow remember to open the debug log and look at what is going on.

---

Also see https://github.com/UnlimitedHugs/RimworldHugsLib/issues/110

**Comment by pardeike** [comment]
How is this related to the Harmony mod?

**Comment by Vectorial1024** [comment]
I kinda feel like this belongs to the "you should know" category; like, I will just put this here, until someone can solve it.

It is not very directly related to Harmony, but given how "core" Harmony is when talking about modded games, would be good to put it here because not able to see error messages is (to me) a "core" problem.

But feel free to close/delete this if you think this is off-topic.

**Comment by pardeike** [comment]
The thing is, Harmony or Harmony mod does not alter the Log.Error method. And you can verify this with a minimal setup. You need to explain your situation because I am not sure I understand what the issue is.

**Comment by Vectorial1024** [comment]
> Harmony or Harmony mod does not alter the Log.Error method

This I agree. I am not expecting Harmony to touch the Log.Error method before I post this, just that the "core" property is quite related.

I think I got ahead of myself, and have mumbled over words.

Closing this.
