### ISSUE TITLE
There is no 1.0 Version Support

### ISSUE THREAD

**Issue by KnightVanKumAlot** [pardeike/HarmonyRimWorld#6]
I am new to all of its programming / making mods and since I wanted an easier start, I choose Rimworld Mods (have simple text displayed or otherwise), but I wanted to make a compatible one for 1.0 and 1.1, but Harmony only supports 1.1. Is there a way to get a version that supports Mods from 1.0 that doesnt have been updated yet.
Maybe I'm just doing something wrong, but if so, I don't know what it is.

**Comment by pardeike** [comment]
https://gist.github.com/pardeike/08ff826bf40ee60452f02d85e59f32ff
