### ISSUE TITLE
Odd Exceptions

### ISSUE THREAD

**Issue by Quamatoc** [pardeike/HarmonyRimWorld#8]
Either my RimWorld (1.1.2654) is broken or the Harmony mod is. Either way I do it two Exceptions  appear:
`Exception loading from System.Xml.Xml.Element: System.MissingMethoException: Default constructor not found for type System.String at System.RuntimeType.CreateInstanceMono (System.Boolean nonpublic) [0x0007b] in <567df3e0919241ba98db88bec4c6696f>:0 `

`Attempt to use string packageid to refer to field packageid in type Verse.ModMetaData+ModMetaDataInternal; xml tags are now case-sensitive. XML:<modMetaData><name>SpiderCamp's`  

I'm not even sure what these signals mean. I hope you could help me. Thanks in advance.

**Comment by pardeike** [comment]
And how is that related to Harmony and thus mod?
